name: DHT Simulation Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 2 * * *'

jobs:
  sim:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      matrix:
        run: [1, 2, 3]
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.1
        
    - name: test
      run: zig build test
      
    - name: gen params
      id: p
      run: |
        S=$((GITHUB_RUN_NUMBER + ${{ matrix.run }} + $(date +%s)))
        P=$((10 + S % 41))
        R=$((50 + S % 151))
        echo "s=$S p=$P r=$R t=180" | tee /dev/stderr
        echo "seed=$S" >> $GITHUB_OUTPUT
        echo "peers=$P" >> $GITHUB_OUTPUT
        echo "rate=$R" >> $GITHUB_OUTPUT
        
    - name: sim
      run: |
        echo "run ${{ matrix.run }}: ${{ steps.p.outputs.peers }}p ${{ steps.p.outputs.rate }}r 15m"
        zig build sim -- --duration 180 --peers ${{ steps.p.outputs.peers }} --rate ${{ steps.p.outputs.rate }} --seed ${{ steps.p.outputs.seed }}
        
    - name: clean
      if: always()
      run: rm -f .dht_peers_*

  done:
    runs-on: ubuntu-latest
    needs: sim
    if: always()
    steps:
    - run: |
        echo "sim: ${{ needs.sim.result }}"
        test "${{ needs.sim.result }}" = "success"
